window.cities = {
  'San Francisco': 'blue',
  'Chicago': 'blue',
  'Atlanta': 'blue',
  'Montreal': 'blue',
  'New York': 'blue',
  'Washington': 'blue',
  'London': 'blue',
  'Madrid': 'blue',
  'Paris': 'blue',
  'Essen': 'blue',
  'Milan': 'blue',
  'St. Petersburg': 'blue',
  'Los Angeles': '#deaf16',
  'Mexico City': '#deaf16',
  'Miami': '#deaf16',
  'Bogota': '#deaf16',
  'Lima': '#deaf16',
  'Santiago': '#deaf16',
  'Sao Paulo': '#deaf16',
  'Buenos Aires': '#deaf16',
  'Lagos': '#deaf16',
  'Kinshasa': '#deaf16',
  'Khartoum': '#deaf16',
  'Johannesburg': '#deaf16',
  'Algiers': 'black',
  'Cairo': 'black',
  'Istanbul': 'black',
  'Moscow': 'black',
  'Tehran': 'black',
  'Baghdad': 'black',
  'Riyadh': 'black',
  'Karachi': 'black',
  'Mumbai': 'black',
  'Delhi': 'black',
  'Kolkata': 'black',
  'Chennai': 'black',
  'Bangkok': 'red',
  'Jakarta': 'red',
  'Beijing': 'red',
  'Shanghai': 'red',
  'Hong Kong': 'red',
  'Ho Chi Minh City': 'red',
  'Seoul': 'red',
  'Taipei': 'red',
  'Manila': 'red',
  'Sydney': 'red',
  'Tokyo': 'red',
  'Osaka': 'red',
};
